import tkinter as tk
from tkinter import *
from tkinter import messagebox
from tkinter import ttk
from User import User
import Event
import os
stocks="TEAR,SMA,CABG,UAPH,FSL.B,DRY,SUAI,PRAI,NGD,IWA,SPOK,NP,INPC,AMZGQ,NLC,FENC,ORA,ZIPR,OHAI,CPNO,MPCCQ,MKTX,ATB,USSPQ,MTL,GME.B,LONG,FOXH,DWA,CLMS,BBW,XNNHQ,NRF,GBCS,CUBE,TWGP,SHO,VNUS,BDAY,LOCMQ,JRJC,ICOPQ,GGBMQ,ANSW,TPGI,RTWIQ,ILSE,GKIS,PSBH,INVA,ARCC,ACFC,YMI,PSPT,NVSL,PRSG,CLWA,JOBS,JMDT,CPL,VSCN,TTM,VLLY,EEEE,BECN,SQBGQ,SPSX,BLIBQ,CMNR,STON,KUHM,OCLR,IOC,TSTC"
stocks=stocks.split(",")

